force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>An object to store details of a survey.</description>
    <label>Survey</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>Text(0)</defaultValue>
    <label>Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyResponseController.cls
public with sharing class SurveyResponseController {

    public static void updateSurveyScore(Map<Id, Survey_Response__c> responseMap) {
        Set<Id> surveyIdSet = new Set<Id>();
        try {
            for(Survey_Response__c response : responseMap.values()) {
                surveyIdSet.add(response.Survey__c);
            }
            List<Survey__c> surveyList = [SELECT Id, Score__c, (SELECT Value__c FROM Survey_Responses__r) FROM Survey__c WHERE Id IN :surveyIdSet];
            List<Survey__c> surveyListToUpdate = new List<Survey__c>();
    
            for(Survey__c survey : surveyList) {
                Integer finalScore = 0;
                for(Survey_Response__c response : survey.Survey_Responses__r) {
                    finalScore = finalScore + Integer.valueOf(response.Value__c);
                }
                Survey__c surveyToUpdate = new Survey__c();
                surveyToUpdate.Id = survey.Id;
                surveyToUpdate.Score__c = String.valueOf(finalScore / surveyList.size());
                surveyListToUpdate.add(surveyToUpdate);
            }
    
            if(surveyListToUpdate.size() > 0) {
                update surveyListToUpdate;
            }
        } catch(Exception ex) {
            System.debug(ex);
        }
    }

}