force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>An object to store details of a survey.</description>
    <label>Survey</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Survey Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Radio Button</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>An objecto to store questions to be used in a survey.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>false</fullName>
                <label>Checkbox</label>
            </value>
            <value>
                <fullName>true</fullName>
                <label>Radio-button</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

changed-sources/force-app/main/default/classes/SurveyControllerTest.cls
/**
* @description test method for SurveyController class
* @author Akshay Gupta
*/
@isTest
public class SurveyControllerTest {

    /**
    *@description method for preparing data
    *
    */
    @TestSetup
    static void prepareData(){
        User testUser = new User(Alias = 'standt', Email='standarduser@testorgmail.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorgmail.com');
        insert testUser;    

        Survey__c survey = new Survey__c();
        survey.Name = 'Product Survey';
        survey.Status__c = 'Assigned';
        survey.Assign_To__c = testUser.Id;
        insert survey;
        
        List<Survey_Question__c> questionList = new List<Survey_Question__c>();
        questionList.add(new Survey_Question__c(Name = 'How much you would rate our product?', Survey__c = survey.Id, Response_Type__c = 'Radio-button'));
        questionList.add(new Survey_Question__c(Name = 'How much you would rate our service?', Survey__c = survey.Id, Response_Type__c = 'Radio-button'));
        insert questionList;

        List<Survey_Answer__c> answerList = new List<Survey_Answer__c>();
        answerList.add(new Survey_Answer__c(Name = '1', Survey_Question__c = questionList[0].Id));
        answerList.add(new Survey_Answer__c(Name = '2', Survey_Question__c = questionList[0].Id));
        answerList.add(new Survey_Answer__c(Name = '3', Survey_Question__c = questionList[0].Id));
        answerList.add(new Survey_Answer__c(Name = '4', Survey_Question__c = questionList[0].Id));
        answerList.add(new Survey_Answer__c(Name = '5', Survey_Question__c = questionList[0].Id));                                
        answerList.add(new Survey_Answer__c(Name = '1', Survey_Question__c = questionList[1].Id));
        answerList.add(new Survey_Answer__c(Name = '2', Survey_Question__c = questionList[1].Id));
        answerList.add(new Survey_Answer__c(Name = '3', Survey_Question__c = questionList[1].Id));
        answerList.add(new Survey_Answer__c(Name = '4', Survey_Question__c = questionList[1].Id));
        answerList.add(new Survey_Answer__c(Name = '5', Survey_Question__c = questionList[1].Id));
        insert answerList;   

    }

    /**
    *@description test method checking if the survey is assigned to user
    *
    */
    public static testMethod void testGetDetails() {
        List<User> userList = [SELECT Id FROM User WHERE UserName='standarduser@testorgmail.com' LIMIT 1];

        Test.startTest();

        System.runAs(userList[0]) {
            SurveyController.SurveyWrapper wrapper = SurveyController.getDetails();

            System.assertEquals(wrapper.title, [SELECT Name FROM Survey__c][0].Name, 'Survey should be assigned');
        }
        
        Test.stopTest();
    }

    /**
    *@description test method simulating response submission
    *
    */
    @isTest
    public static void testSubmitResponses() {
        List<User> userList = [SELECT Id FROM User WHERE UserName='standarduser@testorgmail.com' LIMIT 1];
        List<Survey_Question__c> questionList = [SELECT Id, Survey__c FROM Survey_Question__c LIMIT 2];

        Test.startTest();

        System.runAs(userList[0]) {
            List<SurveyController.ResponseWrapper> wrapperList = new List<SurveyController.ResponseWrapper>();
            
            SurveyController.ResponseWrapper wrapper1 = new SurveyController.ResponseWrapper();
            wrapper1.questionId = questionList[0].Id;
            wrapper1.surveyId = questionList[0].Survey__c;
            wrapper1.response = '4';

            SurveyController.ResponseWrapper wrapper2 = new SurveyController.ResponseWrapper();
            wrapper2.questionId = questionList[1].Id;
            wrapper2.surveyId = questionList[1].Survey__c;
            wrapper2.response = '3';

            wrapperList.add(wrapper1);  
            wrapperList.add(wrapper2);  
            
            SurveyController.submitResponses(JSON.serialize(wrapperList));

            System.assertEquals([SELECT Status__c FROM Survey__c][0].Status__c, 'Closed', 'Survey status should be updated to closed');
        }
        
        Test.stopTest();
    }

    /**
    *@description test method simulating exception
    *
    */
    @isTest
    public static void testGenerateException() {
        try {
            SurveyController.submitResponses(null);
        } catch(Exception ex) {
            System.assertEquals('System.AuraHandledException', ex.getTypeName(), 'Exception should be thrown');
        }
    }    

}