force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>An object to store details of a survey.</description>
    <label>Survey</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Survey Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Radio Button</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>An objecto to store questions to be used in a survey.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>false</fullName>
                <label>Checkbox</label>
            </value>
            <value>
                <fullName>true</fullName>
                <label>Radio-button</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveyController.cls
/**
* @description Controller class for SurveyComponent
* @author Akshay Gupta
*/
public with sharing class SurveyController {
    
    /**
    * @description Method for getting the details for survey assigned to the running user.
    * 
    */
    @AuraEnabled(cacheable=true)
    public static SurveyWrapper getDetails() {
        Set<Id> questionIdSet = new Set<Id>();
        SurveyWrapper surveyWrapper = new SurveyWrapper();
        List<QuestionWrapper> questionWrapperList = new List<QuestionWrapper>();
        List<Survey_Question__c> questionList = new List<Survey_Question__c>();
        try {

            Id assigneeUserId = UserInfo.getUserId();

            Survey__c survey = [SELECT Id, Name, (SELECT Id FROM Survey_Questions__r) FROM Survey__c WHERE Assign_To__c =: assigneeUserId AND Status__c = 'Assigned' WITH SECURITY_ENFORCED].get(0);

            for(Survey_Question__c question : survey.Survey_Questions__r) {
                questionIdSet.add(question.Id);
            }

            if(questionIdSet.size() > 0) {
                questionList = [SELECT Id, Name, Response_Type__c, (SELECT Id, Name FROM Survey_Answers__r ORDER BY Name ASC) FROM Survey_Question__c WHERE Id IN :questionIdSet];                
            }

            if(questionList.size() > 0) {
                for(Survey_Question__c question : questionList) {
                    QuestionWrapper wrapper = new QuestionWrapper();
                    wrapper.questionId = question.Id;
                    wrapper.name = question.Name;
                    wrapper.responseType = question.Response_Type__c == 'Checkbox' ? false : true;
                    wrapper.answers = question.Survey_Answers__r;
                    questionWrapperList.add(wrapper);
                }
            }

            surveyWrapper.surveyId = survey.Id;
            surveyWrapper.title = survey.Name;
            surveyWrapper.questions = questionWrapperList;

            return surveyWrapper;

        } catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    } 

    /**
    * @description Method for handling the submission of response(s)
    * 
    */    
    @AuraEnabled
    public static void submitResponses(String responseWrapper) {
        List<Survey_Response__c> responseList = new List<Survey_Response__c>();       
        try {
            List<ResponseWrapper> responseWrapperList = (List<ResponseWrapper>)JSON.deserialize(responseWrapper, List<ResponseWrapper>.class);

            for(ResponseWrapper wrapper : responseWrapperList) {
                Survey_Response__c response = new Survey_Response__c();
                response.Value__c = wrapper.response;
                response.Survey_Question__c = wrapper.questionId;
                response.Survey__c = wrapper.surveyId;
                responseList.add(response);
            }

            if(responseList.size() > 0) {
                insert responseList;
            }

            Survey__c survey = new Survey__c();
            survey.Id = responseWrapperList[0].surveyId;
            survey.Status__c = 'Closed';
            update survey;

        } catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    } 

    /**
    * @description Wrapper class containing survey details and QuestionWrapper.
    * 
    */        
    public class SurveyWrapper {
        @AuraEnabled public String surveyId;
        @AuraEnabled public String title;
        @AuraEnabled public List<QuestionWrapper> questions;
    }

    /**
    * @description Wrapper class containing the question and answers' details.
    * 
    */        
    public class QuestionWrapper {
        @AuraEnabled public String questionId;
        @AuraEnabled public String name;
        @AuraEnabled public Boolean responseType;
        @AuraEnabled public List<Survey_Answer__c> answers;        
    }    

    /**
    * @description Wrapper class containing survey, question and responses
    * 
    */        
    public class ResponseWrapper {
        @AuraEnabled public String questionId;
        @AuraEnabled public String surveyId;
        @AuraEnabled public String response;
    }

}